version: "3.3"
services:
  db:
    build: ./docker/mysql
    image: mysql:5.7
    container_name: mysql_host
    restart: always
    environment:
      MYSQL_DATABASE: micro_post
      MYSQL_USER: ojisan
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3314:3306"
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
